# Generated by Django 6.0.6 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpeg",
                upload_to="ads/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpeg",
                upload_to="categories/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpeg",
                upload_to="products/",
                verbose_name="image",
            ),
        ),
    ]
